[deployment]
pattern = "DEV"  #possible values, DEV,HA,HA_WITH_ANALYTICS
hostname = "localhost"

[super_admin]
username = "admin"
password = "admin"
create_super_admin = true

[user_store]
type = "database"

[database.shared_db]    # Common database for registry and userstore
type = "mysql"
hostname = "mysql.example.com"
database = "wso2isdb"
password = "$secret{db_password}"

[secrets]
db_password = "encrypted_value_1"