[deployment]
pattern = "DEV"
hostname = "localhost"

[super_admin]
username = "admin"
password = "admin"

[user_store]
type = "read_write_ldap"
connection_url = "ldap://ldap.example.com:389"
connection_name = "uid=admin,ou=wso2is"
connection_password = "$secret{ldap_password}"
base_dn = "dc=example,dc=com"

[secrets]
ldap_password = "encrypted_value_1"
