[server]
pattern = "DEV"

[super_admin]
username = "admin"
password = "admin"
create_super_admin = false

[user_store]
type = "read_only_ldap"
connection_url = "ldap://ldap.example.com:389"
connection_name = "uid=admin,ou=wso2is"
connection_password = "$secret{ldap_password}"
base_dn = "dc=example,dc=com"

[secrets]
ldap_password = "encrypted_value_1"