[deployment]
pattern = "DEV"

[database.shared_db]
type = "mssql"
hostname = "mssql.example.com"
database = "wso2isdb"
password = "$secret{db_password}"

[database.identity_db]
type = "mssql"
hostname = "mssql.example.com"
database = "wso2isdb"
password = "$secret{db_password}"

[secrets]
db_password = "encrypted_value_2"
