[deployment]
pattern = "DEV"
hostname = "wso2is.example.com"

[super_admin]
username = "admin"
password = "admin"

[database.shared_db]
type = "oracle"
hostname = "oracle.example.com"
database = "wso2isdb"
password = "$secret{db_password}"

[database.identity_db]
type = "oracle"
hostname = "oracle.example.com"
database = "wso2isdb"
password = "$secret{db_password}"

[secrets]
db_password = "encrypted_value_2"
